#library "damage"
#include "zcommon.acs"

Script "PlayerKillEffect" DEATH
{
	Thing_ChangeTID(0, 0);
	SetActivator(0, AAPTR_TARGET);
	if(IsPointerEqual(AAPTR_DEFAULT, AAPTR_TARGET) == false)
	{
		LocalAmbientSound("Feedback/Kill", 127);
	}
}

Script "CheckPain" ENTER
{
	while(true)
	{
		int oldHealth = GetActorProperty(0, APROP_HEALTH) + CheckInventory("Armor");
		delay(1);
		int newHealth = GetActorProperty(0, APROP_HEALTH) + CheckInventory("Armor");
		int damage = oldHealth - newHealth;
	
		if(damage > 0)
			GiveInventory("HealthRegenDelay", 35);
		else if(damage < 0)
			SpawnForced("HealingFX", GetActorX(0), GetActorY(0), GetActorZ(0) + 56.0, 0);
	}
}
Script "CheckHitSounds" ENTER
{
	while(true)
	{
		if(CheckInventory("HitSoundBig") > 0)
		{
			LocalAmbientSound("Feedback/HitBig", 127);
		}
		if(CheckInventory("HitSoundMedium") > 0)
		{
			LocalAmbientSound("Feedback/HitMedium", 127);
		}
		if(CheckInventory("HitSoundSmall") > 0)
		{
			LocalAmbientSound("Feedback/HitSmall", 127);
		}
		TakeInventory("HitSoundBig", 1);
		TakeInventory("HitSoundMedium", 1);
		TakeInventory("HitSoundSmall", 1);
		delay(1);
	}
}