#library "lib"
#include "zcommon.acs"

#libdefine TUTORIAL_LEVELNUM 901

#libdefine PLAYER_TIDOFFSET 1000
#libdefine MAX_PLAYERS 64
#libdefine NUM_WEAPS 5
#libdefine NUM_ACTIVES 4
#libdefine NUM_DASHES 2

#libdefine UTID_MIN 1100
#libdefine UTID_LIMIT 10000

str WEAP_ACTORS[NUM_WEAPS] = 	{"PlasmaCarbine", 	"ParticleSplitter", 	"TeslaSMG", 	"C14", 			"FluxRailgun"};//,		 	"Flamespitter", 	"BeamRifle"};
str WEAP_AMMOS[NUM_WEAPS] = 	{"CarbineAmmo", 	"ShotgunAmmo", 			"SMGAmmo", 		"GammaAmmo",	"RailAmmo"};//,		  	"FlameAmmo", 		"BeamAmmo"};
str DASH_SCRIPTS[NUM_DASHES] = 	{"OmniDash", 		"BlinkDash"};
str DASH_INVENTORY[NUM_DASHES] = {"CVAR_DashOmni", 		"CVAR_DashBlink"};

function int abs (int x)
{
    if (x < 0)
        return -x;
    return x;
}
function int sign (int i)
{
	return ((i > 0) - (i < 0));
}
function void GiveMax(str ammo)
{
	GiveInventory(ammo, GetAmmoCapacity(ammo));
}
function void TakeMax(str ammo)
{
	TakeInventory(ammo, GetAmmoCapacity(ammo));
}
function bool IsGamemode(str gamemode)
{
	if(StrICmp(GetCurrentGameMode(), gamemode) == 0)
		return true;
	return false;
}
function void acs(str scr = "", int arg1 = 0, int arg2 = 0, int arg3 = 0)
{
	ACS_NamedExecuteAlways(scr, 0, arg1, arg2, arg3);
}
function bool playerSpotted(void)
{
	for(int i = PLAYER_TIDOFFSET; i < PLAYER_TIDOFFSET + MAX_PLAYERS; i++)
	{
		if(checkSight(0, i, 0) == true)
			return true;
	}
	return false;
}