#library "loadout"
#include "zcommon.acs"
#import "weapon.acs"
#import "lib.acs"
#import "player.acs"

function void setupActive(bool giveItems)
{
	int abil = GetCVAR("ls_active");
	if(ClassifyActor(0) & ACTOR_BOT)
		abil = random(0, NUM_ACTIVES - 1);
	if(abil < 0 || abil >= NUM_ACTIVES)
		abil = 0;
	PLAYER_ACTIVES[PlayerNumber()] = abil;
	if(giveItems)
	{
		GiveInventory(ACTIVE_INVENTORY[PLAYER_ACTIVES[PlayerNumber()]], 1);
	}
}
function void setupWeapon(bool giveItems)
{
	int weap = GetCVAR("ls_startweap");
	if(ClassifyActor(0) & ACTOR_BOT)
		weap = random(0, NUM_WEAPS - 1);
	if(weap < 0 || weap >= NUM_WEAPS)
		weap = 0;
	PLAYER_WEAPONS[PlayerNumber()] = weap;
	if(giveItems)
	{
		GiveInventory(WEAP_ACTORS[weap], 1);
	}
}
function void setupSidearm(bool giveItems)
{
	int weap = GetCVAR("ls_sideweap");
	if(ClassifyActor(0) & ACTOR_BOT)
		weap = random(0, NUM_SIDEWEAPS - 1);
	if(weap < 0 || weap >= NUM_SIDEWEAPS)
		weap = 0;
	PLAYER_SIDEWEAPONS[PlayerNumber()] = weap;
	if(giveItems)
	{
		GiveInventory(SIDEWEAP_ACTORS[weap], 1);
	}
}
function void setupDash(bool giveItems)
{
	int dash = GetCVAR("ls_dash");
	if(ClassifyActor(0) & ACTOR_BOT)
		dash = random(0, NUM_DASHES - 1);
	if(dash < 0 || dash >= NUM_DASHES)
		dash = 0;
	PLAYER_DASHES[PlayerNumber()] = dash;
	if(giveItems)
	{
		GiveInventory(DASH_INVENTORY[PLAYER_DASHES[PlayerNumber()]], 1);
		ACS_NamedExecuteAlways("DashSetupServer", 0, PLAYER_DASHES[PlayerNumber()]);
		ACS_NamedExecuteAlways("DashSetupClient", 0, PLAYER_DASHES[PlayerNumber()]);
	}
}
function void resetLoadout()
{
	ClearInventory();
	refillAmmo();
	setupWeapon(true);
	setupSidearm(true);
	setupActive(true);
	setupDash(true);
}
function void prepLoadoutForRespawn()
{
	setupWeapon(false);
	setupSidearm(false);
	setupActive(false);
	setupDash(false);
}

Script "DashSetupServer" (int type)
{
	SetActionScript(0, BT_USER1, DASH_SCRIPTS[type]);
	if(type == 1)
		SetActionScript(0, 0, "BlinkActive");
}
Script "DashSetupClient" (int type)
{
	SetActionScript(0, BT_USER1, DASH_SCRIPTS[type]);
	if(type == 1)
		SetActionScript(0, 0, "BlinkActive");
}

Script "LoadoutEnter" ENTER
{
	if(GameType() == GAME_TITLE_MAP)
		terminate;
	resetLoadout();
}
Script "LoadoutRespawn" RESPAWN
{
	if(GameType() == GAME_TITLE_MAP)
		terminate;
	resetLoadout();
}
//Close loadout menu. Resets loadout if match is not in progress (i.e. warmup)
Script "LoadoutMenuClose" (void) NET
{
	if(GetGamemodeState() != GAMESTATE_INPROGRESS)
	{
		resetLoadout();
		print(s:"You can change your loadout in the pause menu.");
	}
	else
	{
		prepLoadoutForRespawn();
		print(s:"Your loadout will change on respawn.");
	}
	/*if(GetCVAR("ls_lockloadouts") == false)
	{
	}
	else
	{
		if(GetGamemodeState() != GAMESTATE_INPROGRESS)
		{
			resetLoadout();
			print(s:"You can change your loadout in the pause menu prior to match start.");
		}
		else
		{
			print(s:"Your loadout will change next match.");
		}
	}*/
}