#library "pickups"
#include "zcommon.acs"
#import "lib.acs"
#import "hud.acs"

#define SPHERE_USED_DELAY 7

function bool checkSphere(void)
{
	bool ret = false; //Assume the player does not have an active item yet.
	for(int i = 0; i < NUM_SPHERES; i++)
	{
		if(CheckInventory(SPHERE_HELD[i]) > 0 || CheckInventory(SPHERE_USING[i]) > 0)
		{
			ret = true;
			//log(s:"found sphere held");
		}
	}
	//If a sphere was just fired, count that as true.
	if(CheckInventory("SphereJustUsed") > 0)
	{
		ret = true;
	}
	return ret;
}
	
Script "CheckForSphere" (void)
{
	SetResultValue(checkSphere());
}
Script "HoldingSphere" (void)
{
	int sphereID = -1;
	for(int i = 0; i < NUM_SPHERES; i++)
	{
		if(CheckInventory(SPHERE_HELD[i]) > 0 || CheckInventory(SPHERE_USING[i]) > 0)
		{
			sphereID = i;
		}
	}
	if(sphereID == -1)
	{
		log(s:"sphere holding error.");
		terminate;
	}
	int ptid = ActivatorTID();
	int utid = UniqueTID(UTID_MIN, UTID_LIMIT);
	SpawnSpotForced(SPHERE_HELDFX[sphereID], 0, utid, 0);
	SetActivator(utid);
	SetPointer(AAPTR_TARGET, ptid);
	while((CheckActorInventory(ptid, SPHERE_HELD[sphereID]) || CheckActorInventory(ptid, SPHERE_USING[sphereID])) && (ClassifyActor(ptid) & ACTOR_ALIVE) && !(ClassifyActor(ptid) & ACTOR_WORLD))
	{
		//Warp(ptid, 32.0, -24.0, 20.0, 0.0, WARPF_NOCHECKPOSITION|WARPF_INTERPOLATE);
		if(CheckActorInventory(ptid, SPHERE_USING[sphereID]))
		{
			SetActorState(utid, "Using", true);
		}
		delay(1);
	}
	SetActorState(utid, "Death", true);
}
Script "UseSphere" (void) NET
{
	for(int i = 0; i < NUM_SPHERES; i++)
	{
		if(CheckInventory(SPHERE_HELD[i]) > 0)
		{
			GiveInventory(SPHERE_USING[i], 1);
			TakeInventory(SPHERE_HELD[i], 1);
			acs(SPHERE_SCRIPTS[i], 0);
		}
	}
}
Script "BotSphereCheck" ENTER
{
	while(true)
	{
		if(ClassifyActor(0) & ACTOR_BOT)
		{
			if(playerSpotted() == true)
			{
				for(int i = 0; i < NUM_SPHERES; i++)
				{
					if(CheckInventory(SPHERE_HELD[i]) > 0)
					{
						GiveInventory(SPHERE_USING[i], 1);
						TakeInventory(SPHERE_HELD[i], 1);
						acs(SPHERE_SCRIPTS[i], 0);
					}
				}	
			}
		}
		delay(1);
	}
}
Script "UseDiscSphere" (void)
{
	PlaySound(0, "Items/DiscSphere/Charge", CHAN_6, 1.0, false);
	PlaySound(0, "Items/DiscSphere/ChargeFar", CHAN_7, 1.0, false);
	delay(12);
	StopSound(0, CHAN_6);
	GiveInventory("SphereJustUsed", 1);
	TakeInventory("DiscSphereInUse", 1);
	for(int i = 0; i < 5; i++)
	{
		GiveInventory("DiscSphereFire", 1);
		delay(3);
	}
	
	delay(SPHERE_USED_DELAY);
	TakeInventory("SphereJustUsed", 1);
}
Script "UseRailSphere" (void)
{
	PlaySound(0, "Items/RailSphere/Charge", CHAN_6, 1.0, false);
	PlaySound(0, "Items/RailSphere/ChargeFar", CHAN_7, 1.0, false);
	GiveInventory("RailSphereCharge", 40);
	for(int i = 0; i < 40; i++)
	{
		delay(1);
		//Make sure the rail cancels if the user dies.
		if(!(ClassifyActor(0) & ACTOR_ALIVE))
			terminate;
	}
	StopSound(0, CHAN_6);
	StopSound(0, CHAN_7);
	GiveInventory("RailSphereFire", 1);
	GiveInventory("SphereJustUsed", 1);
	TakeInventory("RailSphereInUse", 1);
	delay(SPHERE_USED_DELAY);
	TakeInventory("SphereJustUsed", 1);
}
Script "UseLeechSphere" (void)
{
	TakeInventory("LeechSphereInUse", 1);
	GiveInventory("LeechSphereFire", 1);
	GiveInventory("SphereJustUsed", 1);
	delay(SPHERE_USED_DELAY);
	TakeInventory("SphereJustUsed", 1);
}