#library "player"
#include "zcommon.acs"
#import "weapon.acs"
#import "lib.acs"
#import "active.acs"

//Stores the player's ability ID throughout the match.
int PLAYER_ACTIVES[MAX_PLAYERS];
//Stores the player's starting weapon ID throughout the match.
int PLAYER_WEAPONS[MAX_PLAYERS];
//Stores the player's sidearm weapon ID throughout the match.
int PLAYER_SIDEWEAPONS[MAX_PLAYERS];
//Stores the player's dash type ID throughout the match.
int PLAYER_DASHES[MAX_PLAYERS];
//Stores the player's ability cooldown between lives.
int PLAYER_ACTIVECDS[MAX_PLAYERS];

Script "PlayerEnter" ENTER
{
	if(GameType() == GAME_TITLE_MAP)
		terminate;
	Thing_ChangeTID(0, PLAYER_TIDOFFSET + PlayerNumber());
	
}
//Make sure the menu opens on the client for multiplayer to work.
Script "PlayerEnterClient" ENTER CLIENTSIDE
{
	if(GameType() == GAME_TITLE_MAP)
		terminate;
	if(ClassifyActor(0) & ACTOR_BOT)
		terminate;
	if(GetGamemodeState() == 1 || GetGamemodeState() == 0)
		ConsoleCommand("openmenu MatchPrepWeapon");
}
Script "PlayerDeath" DEATH
{
	PLAYER_ACTIVECDS[PlayerNumber()] = CheckInventory("ActiveCDSeconds");
}
Script "PlayerRespawn" RESPAWN
{
	refillAmmo();
	Thing_ChangeTID(0, PLAYER_TIDOFFSET + PlayerNumber());
	GiveInventory(ACTIVE_INVENTORY[PLAYER_ACTIVES[PlayerNumber()]], 1);
	GiveInventory(WEAP_ACTORS[PLAYER_WEAPONS[PlayerNumber()]], 1);
	GiveInventory(SIDEWEAP_ACTORS[PLAYER_SIDEWEAPONS[PlayerNumber()]], 1);
	GiveInventory(DASH_INVENTORY[PLAYER_DASHES[PlayerNumber()]], 1);
	GiveInventory("ActiveCDSeconds", PLAYER_ACTIVECDS[PlayerNumber()]);
	ACS_NamedExecuteAlways("DashSetupServer", 0, PLAYER_DASHES[PlayerNumber()]);
	ACS_NamedExecuteAlways("DashSetupClient", 0, PLAYER_DASHES[PlayerNumber()]);
}
//Player disconnects or spectates
Script "PlayerDisconnect" (int pnum) DISCONNECT
{
	//PLAYER_ACTIVES[pnum] = -1;
	//PLAYER_WEAPONS[pnum] = -1;
	//PLAYER_SIDEWEAPONS[pnum] = -1;
	//PLAYER_DASHES[pnum] = -1;
	//PLAYER_ACTIVECDS[pnum] = 0;
	//Do not let player disconnect, change loadout, and reconnect with same score!
	//SetPlayerScore(pnum, SCORE_FRAGS, 0);
	//SetPlayerScore(pnum, SCORE_DEATHS, 0);
}