#library "tick"
#include "zcommon.acs"
#import "lib.acs"
#import "weapon.acs"
#import "active.acs"

#define BANDOLIER_RESTORE 0.5

//int PLAYER_ACTIVECD_TICS[MAX_PLAYERS];

function void bandolierCheck(void)
{
	for(int i = 0; i < NUM_WEAPS; i++)
	{
		//Check which weapon the player is holding.
		if(StrCmp(GetWeapon(), WEAP_ACTORS[i]) == 0)
		{
			//If the player a. has a bandolier and b. is out of ammo for their equiped weapon
			if(CheckInventory("Bandolier") > 0 && CheckInventory(WEAP_AMMOS[i]) < 1)
			{
				//Refill the ammo and use the bandolier
				GiveInventory(WEAP_AMMOS[i], GetAmmoCapacity(WEAP_AMMOS[i]) * BANDOLIER_RESTORE);
				TakeInventory("Bandolier", 1);
				LocalAmbientSound("Weapon/AmmoFill", 1.0);
				acs("DisplayAmmoRefilledMessage");
			}
		}
	}
	for(i = 0; i < NUM_SIDEWEAPS; i++)
	{
		//Check which weapon the player is holding.
		if(StrCmp(GetWeapon(), SIDEWEAP_ACTORS[i]) == 0)
		{
			//If the player a. has a bandolier and b. is out of ammo for their equiped weapon
			if(CheckInventory("Bandolier") > 0 && CheckInventory(SIDEWEAP_AMMOS[i]) < 1)
			{
				//Refill the ammo and use the bandolier
				GiveInventory(SIDEWEAP_AMMOS[i], GetAmmoCapacity(SIDEWEAP_AMMOS[i]) * BANDOLIER_RESTORE);
				TakeInventory("Bandolier", 1);
				LocalAmbientSound("Weapon/AmmoFill", 1.0);
				acs("DisplayAmmoRefilledMessage");
			}
		}
	}
}

function void tickHealthRegen(void)
{
	int regenDelay = 6;
	int regenRateDelay = 6;
		
	if(Timer() % regenDelay == 0)
	{
		TakeInventory("HealthRegenDelay", 1);
	}
	if(Timer() % regenRateDelay == 0)
	{
		if(GetActorProperty(0, APROP_HEALTH) < GetActorProperty(0, APROP_SPAWNHEALTH) && CheckInventory("HealthRegenDelay") < 1)
		{
			GiveInventory("HealthUnlagged", 1);
		}
	}
}

function void tickMainAmmoRegen(void)
{
	//Refills energy when the player has not fired a weapon in a while.
	if(CheckInv("MainAmmoRegenCD") == 1)
	{
		//And plays this sound.
		LocalAmbientSound("Weapon/AmmoFill", 1.0);
		refillMainAmmo();
	}
	//How many tics before your energy begins replenishing.
	TakeInventory("MainAmmoRegenCD", 1);
}

function void tickSideAmmoRegen(void)
{
	//Refills energy when the player has not fired a weapon in a while.
	if(CheckInv("SideAmmoRegenCD") == 1)
	{
		//And plays this sound.
		LocalAmbientSound("Weapon/AmmoFill", 1.0);
		refillSideAmmo();
	}
	//How many tics before your energy begins replenishing.
	TakeInventory("SideAmmoRegenCD", 1);
}

//This whole system needs to be redone probably.
/*function void tickActionCD(void)
{
	PLAYER_ACTIVECD_TICS[PlayerNumber()] += 1;
	acs("SyncActiveTics", PLAYER_ACTIVECD_TICS[PlayerNumber()]);
	if(PLAYER_ACTIVECD_TICS[PlayerNumber()] >= 35)
	{
		PLAYER_ACTIVECD_TICS[PlayerNumber()] = 0;
		acs("SyncActiveTics", PLAYER_ACTIVECD_TICS[PlayerNumber()]);
		if(PLAYER_ACTIVECD[PlayerNumber()] > 0)
		{
			PLAYER_ACTIVECD[PlayerNumber()] = PLAYER_ACTIVECD[PlayerNumber()] - 1;
			ACS("SyncActiveCD", PLAYER_ACTIVECD[PlayerNumber()] - 1);
		}
	}
}
//This whole system needs to be redone probably.
Script "SyncActiveTics" (int value) CLIENTSIDE
{
	PLAYER_ACTIVECD_TICS[PlayerNumber()] = value;
}*/

function void tickActionCD(void)
{
	GiveInventory("ActiveCDTics", 1);
	if(CheckInventory("ActiveCDTics") >= 35)
	{
		TakeMax("ActiveCDTics");
		TakeInventory("ActiveCDSeconds", 1);
	}
}

function void tickAltCD(void)
{
	GiveInventory("MainAltCDTics", 1);
	if(CheckInventory("MainAltCDTics") >= 35)
	{
		TakeMax("MainAltCDTics");
		TakeInventory("MainAltCD", 1);
	}
	GiveInventory("SideAltCDTics", 1);
	if(CheckInventory("SideAltCDTics") >= 35)
	{
		TakeMax("SideAltCDTics");
		TakeInventory("SideAltCD", 1);
	}
	TakeInventory("SharedAltFireCD", 1);
}

function void applySpeedModifiers(void)
{
	int speed = 1.0;
	if(checkInv("TeslaSpeedBoostTics") > 0)
	{
		speed += 0.2;
	}
	SetActorProperty(0, APROP_SPEED, speed);
	TakeInventory("TeslaSpeedBoostTics", 1);
}

function void spawnCanisterFX(void)
{
	int latspread = 12.0;
	SpawnForced("CanisterDebuffFX", GetActorX(0) + Random(-latspread, latspread), GetActorY(0) + Random(-latspread, latspread), GetActorZ(0) + 24.0, 0, 0);
}

script "CooldownTimers" ENTER
{
	while(true)
	{
		if(ClassifyActor(0) & ACTOR_ALIVE)
		{
			TakeInventory("OmniDashCD", 1);
			TakeInventory("WarpDashCD", 1);
			TakeInventory("HRailCharge", 1);
			TakeInventory("IonRebounderEmpoweredTics", 1);
			tickMainAmmoRegen();
			tickSideAmmoRegen();
			bandolierCheck();
			tickHealthRegen();
			tickActionCD();
			tickAltCD();
			
			if(CheckInventory("CanisterDebuffTics") > 0)
			{
				spawnCanisterFX();
			}
			TakeInventory("CanisterDebuffTics", 1);
			
			applySpeedModifiers();
			
			/*if(CheckInventory("IsDashing") > 0)
			{
				SpawnSpotFacingForced("DashTrail", 0, 0);
				TakeInventory("IsDashing", 1);
			}*/
		}
		delay(1);
	}
}